#------------DATASET CONFIG-------------
DATASET:
    NAME: "CatVsDog"
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
    NUM_CLASSES: 2
    IMG_DIR: "/data/yangqi/dataset/CatVsDog_Kaggle/"
    ANNOTATIONS_FILE: "data"
    BASE_SIZE: 224

#-------------TRAIN CONFIG--------------
# 在这种经常改变的代码中，放到argparse内
# TRAIN:
#     EPOCHS: 100
#     BATCH_SIZE: 120
#     NUM_WORKERS: 8
# SOLVER:
#     LR: 0.0001 
MODEL:
    MODEL_NAME: "ResNet101"


        
OUTPUT_DIR: "output"
CHECKPOINT_DIR: "output/checkpoint"
PLOT_DIR: "output/plot_data"
LOG_DIR: "log"
